flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:Sentenai/reinforce.git
    commit: 'a25abbaa522051aaf0532d3abc439b885599be67'
  extra-dep: true
- location:
    git: git@github.com:stites/gym-http-api.git
    commit: '93ce33'
  subdirs:
    - binding-hs
extra-deps:
- accelerate-1.0.0.0
- accelerate-llvm-1.0.0.0
- accelerate-llvm-native-1.0.0.0
- chaselev-deque-0.5.0.5
- llvm-hs-4.0.1.0
- tensorflow-0.1.0.2
- tensorflow-core-ops-0.1.0.0
- tensorflow-opgen-0.1.0.0
- tensorflow-ops-0.1.0.0
- tensorflow-proto-0.1.0.0
resolver: lts-8.15
